# Generated by Django 4.1 on 2024-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=90),
        ),
    ]
