# Generated by Django 4.1 on 2024-12-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
